# syntax=docker/dockerfile:1
FROM node:18
WORKDIR /code

COPY *.json .
COPY src src
COPY prisma prisma

RUN npm i
RUN npx prisma generate
RUN npm run build
RUN npm prune --production

CMD npx prisma migrate deploy && node dist/main.js
